### ISSUE TITLE
Not working in LinuxMint 20

### ISSUE THREAD

**Issue by spartan** [pkkid/pygrid#26]
System:
```
System:    Kernel: 5.4.0-48-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal
```

Error on run:
```bash
$ ./pygrid.py 
./pygrid.py:81: PyGIDeprecationWarning: GObject.io_add_watch is deprecated; use GLib.io_add_watch instead
  GObject.io_add_watch(self.root.display, GObject.IO_IN, self._check_event)
./pygrid.py:81: PyGIDeprecationWarning: GObject.IO_IN is deprecated; use GLib.IO_IN instead
  GObject.io_add_watch(self.root.display, GObject.IO_IN, self._check_event)
PyGrid running. Press CTRL+C to cancel.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 671, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "./pygrid.py", line 102, in _check_event
    command = self.keys[event.detail]
KeyError: 37
```

**Comment by spartan** [comment]
I managed to fix the deprecated warnings but no luck with shortcuts:


I am on X and it worked in another LinuxMint installation:
```
echo $XDG_SESSION_TYPE
```
```
x11
```

**Comment by spartan** [comment]
Nevermind, I've installed QuickTile and it worked flawlessly.
